### ISSUE TITLE
Ikea conversion , training and testing splits,

### ISSUE THREAD

**Issue by ghost** [qxcv/pose-prediction#2]
Hi Sam,

I am going to prepare ikea dataset not using `ikea_action_data.h5` 
but using provided `IkeaClipsDB.mat` or video files directly after pose extraction, I take a look in `convert_ikea.m file` I could not figure out  which lines are 
for pose parameterisation from the joints location to the relative positions.  
and It is mentioned that you used 11 actors for training and the rest for testing,   
there are three folders provided by Ikea ,  which ones are for training
I would appreciate your comments, 

Thanks,
Samira

**Comment by qxcv** [comment]
Hi Samira. I believe convert_ikea.m just writes joint coordinates directly; reparameterisation of the skeleton is performed in [`p2d_loader.py:preprocess_sequence()`](https://github.com/qxcv/pose-prediction/blob/master/keras/p2d_loader.py#L77-L175). After taking out the bits that are normally disabled (e.g. polar coordinates), the function looks like this:

```python
def preprocess_sequence(poses,
                        skip,
                        parents,
                        polar=False,
                        smooth_sigma=False,
                        head_vel=True,
                        hrm_mat=None):
    """Preprocess a sequence of 2D poses to have more tractable representation.
    `parents` array is used to calculate output entries which are
    parent-relative joint locations. Note that standardisation will have to be
    performed later."""
    # Poses should be T*(XY)*J
    assert poses.ndim == 3, poses.shape
    assert poses.shape[1] == 2, poses.shape

    # if smooth_sigma: (always supplied)
    # Remove high freq noise with reasonably narrow Gaussian. Channel-wise,
    # so can be applied before anything else.
    pflat = poses.reshape((poses.shape[0], np.prod(poses.shape[1:])))
    psmooth = gauss_filter(pflat, sigma=smooth_sigma)
    poses = psmooth.reshape(poses.shape)

    # Scale so that person roughly fits in 1x1 box at origin
    scale = (np.max(poses, axis=2) - np.min(poses, axis=2)).flatten().std()
    assert 1e-3 < scale < 1e4, scale
    offset = np.mean(np.mean(poses, axis=2), axis=0).reshape((1, 2, 1))
    norm_poses = (poses - offset) / scale

    # will be updated below if necessary
    head_locs = None

    # Compute actual data (relative offsets are easier to learn)
    relpose = np.zeros_like(norm_poses)
    # if head_vel: (always true)
    # Record delta from frame which is <skip> steps in the past
    relpose[skip:, :, 0] \
        = norm_poses[skip:, :, 0] - norm_poses[:-skip, :, 0]
    # (x, y) position that head starts in
    # required for head reconstruction when using a velocity-based head
    # parameterisation
    head_locs = norm_poses[:, :, 0]

    # Other norm_poses record delta from parents
    for jt in range(1, len(parents)):
        pa = parents[jt]
        relpose[:, :, jt] = norm_poses[:, :, jt] - norm_poses[:, :, pa]

    # Collapse in last two dimensions, interleaving X and Y coordinates
    shaped = relpose.reshape((relpose.shape[0], -1))

    return shaped, offset, scale, head_locs
```

As for test/val subjects, they're listed in [`IkeaDB.m`](https://github.com/qxcv/pose-prediction/blob/ea18e1968d471258a5a5ab2f97a4b175cbeabf5a/io/IkeaDB.m#L21-L25). I think there are also `is_train` and `subject_id` flags in the `.h5` file for Ikea FA. If you run `h5dump -H ikea_action_data.h5` (which displays headers/structure of a HDF5 file) then it should show you where those flags are in the HDF5 hierarchy.

**Comment by ghost** [comment]
Thank you so much Sam ,
